main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('<slug:person_slug>/', views.HOME, name='home'),
    path('<slug:person_slug>/about/', views.ABOUT, name='about'),
    path('<slug:person_slug>/portfolio/', views.PORTFOLIO, name='portfolio'),
    path('<slug:person_slug>/contact/', views.CONTACT, name='contact'),
    path('<slug:person_slug>/blog/', views.BLOG, name='blog'),
    path('<slug:person_slug>/blog/<slug:blog_slug>', views.BLOG_DETAIL, name='blog_detail'),
    path('contact/contact-mail-send/', views.CONTACT_EMAIL, name='send_email')
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from django.views.static import serve

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('', include('main.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

handler404 = 'main.views.ERROR_404'

main/models.py
from django.db import models
from django_countries.fields import CountryField
from ckeditor.fields import RichTextField
from django.core.validators import FileExtensionValidator
from django.db.models.signals import pre_save
from django.utils.text import slugify

class Person(models.Model):
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(unique=True, max_length=150)
    name_display = models.CharField(max_length=100, null=True)
    date_of_birth = models.DateField(null=True, blank=True)
    profile_pic = models.ImageField(default='user_images/default.jpg', upload_to='user_images', blank=True)

    title = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    country = CountryField(blank_label='(select country)', null=True, blank=True)

    phone = models.CharField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    languages = models.CharField(max_length=100, null=True, blank=True)

    freelance = models.CharField(max_length=5, choices=(("yes", "Available"),("no", "Unavailable")), default='no')
    resume = models.FileField(null=True, blank=True, validators=[FileExtensionValidator(['pdf','docx']), ], upload_to='resumes')
    slug = models.SlugField(default='', max_length=100)
    google_map_embed_src = models.CharField(max_length=800, null=True, blank=True)

    def __str__(self):
        return self.name_display

class Achievements(models.Model):
    who = models.ForeignKey(Person, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, null=True, blank=True)
    description = models.CharField(max_length=60, null=True, blank=True)

class Skills(models.Model):
    who = models.ForeignKey(Person, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    percent = models.PositiveSmallIntegerField(null=True, blank=True)

class Education(models.Model):
    who = models.ForeignKey(Person, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    ongoing = models.BooleanField(default=False)
    institution = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

class Experience(models.Model):
    who = models.ForeignKey(Person, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    ongoing = models.BooleanField(default=False)
    company = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

class Project_Category(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    icon = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name

class Project(models.Model):
    who = models.ForeignKey(Person, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    category = models.ForeignKey(Project_Category, on_delete=models.CASCADE)
    preview_pic = models.ImageField(default='project_images/default.jpg', upload_to='project_images', blank=True)
    client = models.CharField(max_length=50, null=True, blank=True)
    languages = models.CharField(max_length=200, null=True, blank=True)
    priority = models.PositiveSmallIntegerField(default=2)

    preview_text = models.CharField(max_length=50, null=True, blank=True)
    preview_link = models.CharField(max_length=200, null=True, blank=True)

    source_code_text = models.CharField(max_length=50, null=True, blank=True)
    source_code_link = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.who.name_display + "-" + self.category.name + "-" + self.title

class Project_slide(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    category = models.CharField(max_length=10, choices=(("img", "Image"),("yt_link", "YouTube Video"),("vid", "Uploaded Video")), default='img')
    image = models.ImageField(null=True, upload_to='project_images', blank=True)
    youtube_embed_link = models.CharField(max_length=600, null=True, blank=True)
    video = models.FileField(null=True, blank=True, validators=[FileExtensionValidator(['mp4','mkv','avi','flv']), ], upload_to='videos')
    video_poster = models.ImageField(null=True, upload_to='project_images', blank=True)

class Blog(models.Model):
    who = models.ForeignKey(Person, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, null=True, blank=True)
    date = models.DateField(null=True, blank=True)
    tags = models.CharField(max_length=200, null=True, blank=True)
    banner_image = models.ImageField(null=True, upload_to='blog', blank=True)
    banner_image_url = models.CharField(max_length=500, null=True, blank=True)
    slug = models.CharField(max_length=150, null=True, blank=True)
    content = RichTextField()

    def __str__(self):
        return self.who.name_display + "-" + self.title

def return_slug(slug, qs, instance):
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Blog.objects.filter(slug=slug).order_by('-id')
    return_slug(slug, qs, instance)
    return slug

def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, Blog)

class Social_Media(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    icon_class = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

class Social_Media_links(models.Model):
    who = models.ForeignKey(Person, on_delete=models.CASCADE)
    platform = models.ForeignKey(Social_Media, on_delete=models.CASCADE)
    link  = models.CharField(max_length=150, null=True, blank=True)

    def __str__(self):
        return self.who.name_display + "-" + self.platform.name

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from dateutil.relativedelta import relativedelta
from datetime import date
from django.core.mail import send_mail
from django.conf import settings
from . models import *

def HOME(request, person_slug):
    person = get_object_or_404(Person, slug=person_slug)
    context = {
        'person': person,
        'page_no': 1
    }
    return render(request, 'home.html', context)

def ABOUT(request, person_slug):
    person = get_object_or_404(Person, slug=person_slug)
    skills = Skills.objects.filter(who=person).order_by('-percent')
    experience = Experience.objects.filter(who=person).order_by('-end_date')
    education = Education.objects.filter(who=person).order_by('-end_date')
    achievements = Achievements.objects.filter(who=person).order_by('-description')

    person.age = relativedelta(date.today(), person.date_of_birth).years

    context = {
        'person': person,
        'skills': skills,
        'achievements': achievements,
        'experience': experience,
        'education': education,
        'page_no': 2
    }
    return render(request, 'about.html', context)

def PORTFOLIO(request, person_slug):
    person = get_object_or_404(Person, slug=person_slug)
    projects = Project.objects.filter(who=person).order_by('priority')

    context = {
        'person': person,
        'all_projects': projects,
        'page_no': 3
    }
    return render(request, 'portfolio.html', context)

def CONTACT(request, person_slug):
    person = get_object_or_404(Person, slug=person_slug)
    social_links = Social_Media_links.objects.filter(who=person).order_by('platform__name')
    context = {
        'person': person,
        'social_links': social_links,
        'page_no': 4
    }
    return render(request, 'contact.html', context)

def BLOG(request, person_slug):
    person = get_object_or_404(Person, slug=person_slug)
    blogs = Blog.objects.filter(who=person).order_by('-date')

    product_count = blogs.count()
    product_per_page = 9
    extra_pages_count = ((int(product_count/product_per_page)-1) if ((product_count%product_per_page)==0) else int(product_count/product_per_page)) if (product_count>product_per_page) else 0

    context = {
        'person': person,
        'all_blogs': blogs,
        'pages_count': extra_pages_count,
        'page_no': 5
    }
    return render(request, 'blog.html', context)

def BLOG_DETAIL(request, person_slug, blog_slug):
    person = get_object_or_404(Person, slug=person_slug)
    blog = get_object_or_404(Blog, who=person, slug=blog_slug)
    context = {
        'person': person,
        'blog': blog,
        'page_no': 5
    }
    return render(request, 'blog_post.html', context)

def CONTACT_EMAIL(request, person_slug):
    name = request.POST.get('name')
    email = request.POST.get('email')
    subject = request.POST.get('subject')
    message = request.POST.get('message')
    person_id = int(request.POST.get('person'))
    person_email = Person.objects.get(id=person_id).email

    final_message = "You have an email from : " + name + "\nEmail address : " + email + "\nSubject : " + subject + "\nMessage : " + message
    thank_you_msg = "Hi! We have received your email. We will be contacting you shortly. Thanks and take care!"

    send_mail('Contact Form', final_message, settings.EMAIL_HOST_USER, [person_email], fail_silently=False)
    send_mail('Thank you for contacting us', thank_you_msg, settings.EMAIL_HOST_USER, [email], fail_silently=False)
    return redirect('contact')

def ERROR_404(request, exception):
    return render(request, '404.html')

main/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<title>{{person.name_display}}- About</title>
<body class="about">
    <!-- Live Style Switcher Starts - demo only -->
    {% include 'includes/switcher.html' %}
    <!-- Live Style Switcher Ends - demo only -->

    <!-- Header Starts -->
    {% include 'includes/header.html' %}
    <!-- Header Ends -->

    <!-- Page Title Starts -->
    <section class="title-section text-left text-sm-center revealator-slideup revealator-once revealator-delay1">
        <h1>ABOUT <span>ME</span></h1>
        <span class="title-bg">Resume</span>
    </section>
    <!-- Page Title Ends -->

    <!-- Main Content Starts -->
    <section class="main-content revealator-slideup revealator-once revealator-delay1">
        <div class="container">
            <div class="row">
                <!-- Personal Info Starts -->
                <div class="col-12 col-lg-5 col-xl-6">
                    <div class="row">
                        <div class="col-12">
                            <h3 class="text-uppercase custom-title mb-0 ft-wt-600">personal infos</h3>
                        </div>
                        <div class="col-12 d-block d-sm-none">
                            <img src="/media/{{person.profile_pic}}" class="img-fluid main-img-mobile" alt="my picture" />
                        </div>
                        <div class="col-6">
                            <ul class="about-list list-unstyled open-sans-font">
                                <li> <span class="title">first name :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.first_name}}</span> </li>
                                <li> <span class="title">last name :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.last_name}}</span> </li>
                                <li> <span class="title">Age :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.age}} Years</span> </li>
                                <li> <span class="title">Nationality :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.country.name}}</span> </li>
                                <li> <span class="title">Freelance :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.get_freelance_display}}</span> </li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <ul class="about-list list-unstyled open-sans-font">
                                <li> <span class="title">Address :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.address}}</span> </li>
                                <li> <span class="title">phone :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.phone}}</span> </li>
                                <li> <span class="title">Email :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.email}}</span> </li>
                                <li> <span class="title">langages :</span> <span class="value d-block d-sm-inline-block d-lg-block d-xl-inline-block">{{person.languages}}</span> </li>
                            </ul>
                        </div>
                        <div class="col-12 mt-3">
                            <a class="button" href="/media/{{person.resume}}" download>
                                <span class="button-text">Download CV</span>
                                <span class="button-icon fa fa-download"></span>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- Personal Info Ends -->
                <!-- Boxes Starts -->
                <div class="col-12 col-lg-7 col-xl-6 mt-5 mt-lg-0">
                    <div class="row">

                        {% for item in achievements %}
                        <div class="col-6">
                            <div class="box-stats with-margin">
                                <h3 class="poppins-font position-relative">{{item.title}}</h3>
                                <p class="open-sans-font m-0 position-relative text-uppercase">{{item.description}}</p>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
                <!-- Boxes Ends -->
            </div>
            <hr class="separator">
            <!-- Skills Starts -->
            <div class="row">
                <div class="col-12">
                    <h3 class="text-uppercase pb-4 pb-sm-5 mb-3 mb-sm-0 text-left text-sm-center custom-title ft-wt-600">My Skills</h3>
                </div>

                {% for skill in skills %}
                <div class="col-6 col-md-3 mb-3 mb-sm-5">
                    <div class="c100 p{{skill.percent}}">
                        <span>{{skill.percent}}%</span>
                        <div class="slice">
                            <div class="bar"></div>
                            <div class="fill"></div>
                        </div>
                    </div>
                    <h6 class="text-uppercase open-sans-font text-center mt-2 mt-sm-4">{{skill.title}}</h6>
                </div>
                {% endfor %}

            </div>
            <!-- Skills Ends -->
            <hr class="separator mt-1">
            <!-- Experience & Education Starts -->
            <div class="row">
                <div class="col-12">
                    <h3 class="text-uppercase pb-5 mb-0 text-left text-sm-center custom-title ft-wt-600">Experience <span>&</span> Education</h3>
                </div>
                <div class="col-lg-6 m-15px-tb">
                    <div class="resume-box">
                        <ul>

                            {% for exp in experience %}
                            <li>
                                <div class="icon">
                                    <i class="fa fa-briefcase"></i>
                                </div>
                                <span class="time open-sans-font text-uppercase">{{exp.start_date|date:"Y"}} - {% if exp.ongoing == True %}Present{% else %}{{exp.end_date|date:"Y"}}{% endif %}</span>
                                <h5 class="poppins-font text-uppercase">{{exp.title}} <span class="place open-sans-font">{{exp.company}}</span></h5>
                                <p class="open-sans-font">{{exp.description}}</p>
                            </li>
                            {% endfor %}
         
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 m-15px-tb">
                    <div class="resume-box">
                        <ul>

                            {% for ed in education %}
                            <li>
                                <div class="icon"><i class="fa fa-graduation-cap"></i></div>
                                <span class="time open-sans-font text-uppercase">{{ed.start_date|date:"Y"}} - {% if ed.ongoing == True %}Present{% else %}{{ed.end_date|date:"Y"}}{% endif %}</span>
                                <h5 class="poppins-font text-uppercase">{{ed.title}}<span class="place open-sans-font">{{ed.institution}}</span></h5>
                                <p class="open-sans-font">{{ed.description}}</p>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                </div>
            </div>
            <!-- Experience & Education Ends -->
        </div>
    </section>
    <!-- Main Content Ends -->
</body>

{% endblock %}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Template Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,600i,700" rel="stylesheet">

    <link rel="icon" type="image/x-icon" href="/media/{{person.profile_pic}}">
    <!-- Template CSS Files -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/preloader.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/circle.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fm.revealator.jquery.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- CSS Skin File -->
    <link href="{% static 'css/skins/yellow.css' %}" rel="stylesheet">

    <!-- Live Style Switcher - demo only -->
    <link rel="alternate stylesheet" type="text/css" title="blue" href="{% static 'css/skins/blue.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="green" href="{% static 'css/skins/green.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="yellow" href="{% static 'css/skins/yellow.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="blueviolet" href="{% static 'css/skins/blueviolet.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="goldenrod" href="{% static 'css/skins/goldenrod.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="magenta" href="{% static 'css/skins/magenta.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="orange" href="{% static 'css/skins/orange.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="purple" href="{% static 'css/skins/purple.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="red" href="{% static 'css/skins/red.css' %}" />
    <link rel="alternate stylesheet" type="text/css" title="yellowgreen" href="{% static 'css/skins/yellowgreen.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styleswitcher.css' %}" />

    <!-- Modernizr JS File -->
    <script src="{% static 'js/modernizr.custom.js' %}"></script>
</head>

{% block content %}
 
{% endblock %} 

<!-- Template JS Files -->
<script src="{% static 'js/jquery-3.5.0.min.js' %}"></script>
<script src="{% static 'js/styleswitcher.js' %}"></script>
<script src="{% static 'js/preloader.min.js' %}"></script>
<script src="{% static 'js/fm.revealator.jquery.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'js/classie.js' %}"></script>
<script src="{% static 'js/cbpGridGallery.js' %}"></script>
<script src="{% static 'js/jquery.hoverdir.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/blog_pagination.js' %}" defer></script>

</html>

main/templates/home.html
{% extends 'base.html' %}
{% block content %}

<title>{{person.name_display}}- Personal Portfolio</title>
<body class="home">
    <!-- Live Style Switcher Starts - demo only -->
    {% include 'includes/switcher.html' %}
    <!-- Live Style Switcher Ends - demo only -->

    <!-- Header Starts -->
    {% include 'includes/header.html' %}
    <!-- Header Ends -->

    <!-- Main Content Starts -->
    <section class="container-fluid main-container container-home p-0 revealator-slideup revealator-once revealator-delay1">
        <div class="color-block d-none d-lg-block"></div>
        <div class="row home-details-container align-items-center">
            <div class="col-lg-4 bg position-fixed d-none d-lg-block" style="background-image:url(/media/{{person.profile_pic}})"></div>
            <div class="col-12 col-lg-8 offset-lg-4 home-details text-left text-sm-center text-lg-left">
                <div>
                    <img src="/media/{{person.profile_pic}}" class="img-fluid main-img-mobile d-none d-sm-block d-lg-none" alt="my picture" />
                    <h1 class="text-uppercase poppins-font">I'm {{person.name_display}}.<span>{{person.title}}</span></h1>
                    <p class="open-sans-font">{{person.description}}</p>
                    <a class="button" href="{% url 'about' person.slug %}">
                        <span class="button-text">more about me</span>
                        <span class="button-icon fa fa-arrow-right"></span>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- Main Content Ends -->
</body>
{% endblock %}

main/templates/portfolio.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<title>{{person.name_display}}- Portfolio</title>
<body class="portfolio">
    <!-- Live Style Switcher Starts - demo only -->
    {% include 'includes/switcher.html' %}
    <!-- Live Style Switcher Ends - demo only -->

    <!-- Header Starts -->
    {% include 'includes/header.html' %}
    <!-- Header Ends -->

    <!-- Page Title Starts -->
    <section class="title-section text-left text-sm-center revealator-slideup revealator-once revealator-delay1">
        <h1>my <span>portfolio</span></h1>
        <span class="title-bg">works</span>
    </section>
    <!-- Page Title Ends -->
    <!-- Main Content Starts -->
    <section class="main-content text-center revealator-slideup revealator-once revealator-delay1">
        <div id="grid-gallery" class="container grid-gallery">
            <!-- Portfolio Grid Starts -->
            <section class="grid-wrap">
                <ul class="row grid">

                    <!-- Portfolio Item Starts -->
                    {% for project in all_projects %}
                    <li>
                        <figure>
                            <img src="/media/{{project.preview_pic}}" alt="Portolio Image" />
                            <div><span>{{project.title}}</span></div>
                        </figure>
                    </li>
                    {% endfor %}
                    <!-- Portfolio Item Ends -->
                    
                </ul>
            </section>
            <!-- Portfolio Grid Ends -->
            <!-- Portfolio Details Starts -->
            <section class="slideshow">
                <ul>

                    <!-- Portfolio Item Detail Starts -->
                    
                    {% for project in all_projects %}
                    <li>
                        <figure>
                            <!-- Project Details Starts -->
                            <figcaption>
                                <h3>{{project.title}}</h3>
                                <div class="row open-sans-font">
                                    <div class="col-6 mb-2">
                                        <i class="fa fa-file-text-o pr-2"></i><span class="project-label">Project </span>: <span class="ft-wt-600 uppercase">{{project.category.name}}</span>
                                    </div>
                                    {% if project.client %}
                                    <div class="col-6 mb-2">
                                        <i class="fa fa-user-o pr-2"></i><span class="project-label">Client </span>: <span class="ft-wt-600 uppercase">{{project.client}}</span>
                                    </div>
                                    {% endif %}
                                    <div class="col-6 mb-2">
                                        <i class="fa fa-code pr-2"></i><span class="project-label">Langages </span>: <span class="ft-wt-600 uppercase">{{project.languages}}</span>
                                    </div>
                                    {% if project.preview_link %}
                                    <div class="col-6 mb-2">
                                        <i class="fa fa-external-link pr-2"></i><span class="project-label">Preview </span>: <span class="ft-wt-600 uppercase"><a href="{{project.preview_link}}" target="_blank">{{project.preview_text}}</a></span>
                                    </div>
                                    {% endif %}
                                    {% if project.source_code_link %}
                                    <div class="col-6 mb-2">
                                        <i class="fa fa-external-link pr-2"></i><span class="project-label">Source Code </span>: <span class="ft-wt-600 uppercase"><a href="{{project.source_code_link}}" target="_blank">{{project.source_code_text}}</a></span>
                                    </div>
                                    {% endif %}
                                </div>
                            </figcaption>
                            <!-- Project Details Ends -->
                            <!-- Main Project Content Starts -->
                            <div id="slider-{{project.id}}" class="carousel slide portfolio-slider" data-ride="carousel" data-interval="false">
                                <ol class="carousel-indicators">
                                    <li data-target="#slider-{{project.id}}" data-slide-to="0" class="active"></li>

                                    {% for slide in project.project_slide_set.all|dictsort:'category' %}
                                    <li data-target="#slider-{{project.id}}" data-slide-to="{{forloop.counter}}"></li>
                                    {% endfor %}
                                </ol>
                                <!-- The slideshow -->
                                <div class="carousel-inner">

                                    <div class="carousel-item active">
                                        <img src="/media/{{project.preview_pic}}">
                                    </div>

                                    {% for slide in project.project_slide_set.all|dictsort:'category' %}

                                        {% if slide.category == 'yt_link' %}
                                        <div class="carousel-item">
                                            <div class="videocontainer">
                                                <iframe class="youtube-video" src="{{slide.youtube_embed_link}}" allowfullscreen></iframe>
                                            </div>
                                        </div>
                                        {% endif %}

                                        {% if slide.category == 'vid' %}
                                        <div class="carousel-item">
                                            <video id="video" class="responsive-video" controls {% if slide.video_poster %}poster="/media/{{slide.video_poster}}"{% endif %}>
                                                <source src="/media/{{slide.video}}" type="video/mp4">
                                            </video>
                                        </div>
                                        {% endif %}

                                        {% if slide.category == 'img' %}
                                        <div class="carousel-item">
                                            <img src="/media/{{slide.image}}">
                                        </div>
                                        {% endif %}

                                    {% endfor %}
                                </div>
                            </div>
                            <!-- Main Project Content Ends -->
                        </figure>
                    </li>
                    {% endfor %}
                    <!-- Portfolio Item Detail Ends -->

  

                </ul>
                <!-- Portfolio Navigation Starts -->
                <nav>
                    <span class="icon nav-prev"><img src="{% static 'img/projects/navigation/left-arrow.png' %}" alt="previous"></span>
                    <span class="icon nav-next"><img src="{% static 'img/projects/navigation/right-arrow.png' %}" alt="next"></span>
                    <span class="nav-close"><img src="{% static 'img/projects/navigation/close-button.png' %}" alt="close"> </span>
                </nav>
                <!-- Portfolio Navigation Ends -->
            </section>
        </div>
    </section>
    <!-- Main Content Ends -->

</body>
{% endblock %}